FROM containerstack/debian:wheezy
LABEL maintainer="remon@containerstack.io"
LABEL architecture="amd64"
RUN echo 'deb http://deb.debian.org/debian wheezy-backports main' > /etc/apt/sources.list.d/backports.list
