FROM containerstack/debian:armv5-wheezy
LABEL maintainer="remon@containerstack.io"
LABEL architecture="armv5"
RUN echo 'deb http://deb.debian.org/debian wheezy-backports main' > /etc/apt/sources.list.d/backports.list
